default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: meal_time_development

test:
  <<: *default
  database: meal_time_test

production:
  <<: *default
  database: meal_time_production
